### ISSUE TITLE
Localization help needed

### ISSUE THREAD

**Issue by doston0000** [regulaforensics/FaceSDK-iOS#2]
How to change localization, could not find any info in docs in facesdk, found docs for https://docs.regulaforensics.com/ios/localization but string file opens in incorrect format 
<img width="782" alt="Screen Shot 2021-03-23 at 3 52 07 PM" src="https://user-images.githubusercontent.com/16070841/112135571-baa8c780-8bef-11eb-9560-18bf5317d7bf.png">

**Comment by vyakimchik** [comment]
Hi @doston0000,

Sorry for keeping you waiting!

What you need is to create a file named "RegulaSDK.strings", insert IDs of strings you want to localize, then add this file to your project. [Here](https://img.regulaforensics.com/Strings/FaceSDK/2.2/RegulaSDK.strings) is the full list of available strings in the Face SDK.

Also, I've published the [page](https://docs.regulaforensics.com/ios-face/localization) in the docs regarding this query like it's made for Document Reader SDK.

**Comment by vyakimchik** [comment]
Hi @doston0000,

Have you managed to localize strings?

**Comment by pkandrashkou** [comment]
The localization-related information is located [here](https://docs.regulaforensics.com/develop/face-sdk/mobile/localization/ios/) now.

Please take a look at the `Changing Localization` section of the page if you still have any questions regarding the `.strings` file. 

Closing the issue due to inactivity.
